### ISSUE TITLE
error C4996: 'InferenceEngine::Blob::dims': 被声明为已否决

### ISSUE THREAD

**Issue by globalmaster** [SyGoing/LFFD-OpenVINO#1]
你好，我用VS2015、openvino_2019.2.242版本进行编译，报如下错误：

错误	C2664	“int LFFD::detect(cv::Mat &,std::vector<FaceInfo,std::allocator<_Ty>> &,int,int,float,float,int,std::vector<int,std::allocator<int>>)”: 无法将参数 3 从“cv::Size_<int>”转换为“int”	OpenVINO_LFFD	E:\clion_kdevelop\OpenCV\dnn_VS\OpenVINO_LFFD\main.cpp	37	

错误	C2664	“int LFFD::detect(cv::Mat &,std::vector<FaceInfo,std::allocator<_Ty>> &,int,int,float,float,int,std::vector<int,std::allocator<int>>)”: 无法将参数 3 从“cv::Size_<int>”转换为“int”	OpenVINO_LFFD	E:\clion_kdevelop\OpenCV\dnn_VS\OpenVINO_LFFD\main.cpp	67	

错误	C4996	'InferenceEngine::PluginDispatcher::getPluginByDevice': 被声明为已否决	OpenVINO_LFFD	E:\clion_kdevelop\OpenCV\dnn_VS\OpenVINO_LFFD\OpenVINO_LFFD.cpp	58	

错误	C4996	'InferenceEngine::Blob::dims': 被声明为已否决	OpenVINO_LFFD	E:\clion_kdevelop\OpenCV\dnn_VS\OpenVINO_LFFD\OpenVINO_LFFD.cpp	131	

错误	C4996	'InferenceEngine::Blob::dims': 被声明为已否决	OpenVINO_LFFD	E:\clion_kdevelop\OpenCV\dnn_VS\OpenVINO_LFFD\OpenVINO_LFFD.cpp	132	

请问应该用什么版本的OpenVINO？谢谢！

**Comment by SyGoing** [comment]
这个不算是错误，在预处理中加入
项目－－＞项目属性－－＞C/C++－－＞预处理器定义
添加：_CRT_NONSTDC_NO_DEPRECATE和_CRT_SECURE_NO_WARNINGS

**Comment by globalmaster** [comment]
> 这个不算是错误，在预处理中加入
> 项目－－＞项目属性－－＞C/C++－－＞预处理器定义
> 添加：_CRT_NONSTDC_NO_DEPRECATE和_CRT_SECURE_NO_WARNINGS

感谢你的回复，我确认加上这两个定义之后，还是报同样的错，不知道问题出在哪里了。

**Comment by globalmaster** [comment]
> 这个不算是错误，在预处理中加入
> 项目－－＞项目属性－－＞C/C++－－＞预处理器定义
> 添加：_CRT_NONSTDC_NO_DEPRECATE和_CRT_SECURE_NO_WARNINGS

能不能给我发一个VS工程文件或者CMakeList.txt文件？这个问题在Ubuntu平台会出现吗，如何解决？

**Comment by SyGoing** [comment]
我当时没遇到过这个，根据提示貌似是你的函数参数不对应，你检查一下自己的代码

**Comment by SyGoing** [comment]
看了下 这是我代码的问题，我的detect函数没有改过来，对不起 ，我马上改过来，demo.cpp给的是cv::Size输入，我代码是两个int型的

**Comment by globalmaster** [comment]
> 看了下 这是我代码的问题，我的detect函数没有改过来，对不起 ，我马上改过来，demo.cpp给的是cv::Size输入，我代码是两个int型的

resize_h和resize_w未声明

**Comment by SyGoing** [comment]
已经修正

**Comment by globalmaster** [comment]
> 已经修正

我这个C4996的问题，VS并没有提示加上_CRT_SECURE_NO_WARNINGS就可以解决，而且我确信我正确地加上了这个预定义，也没有解决问题。从CV_WINDOW_NORMAL我判断出你的opencv版本为3.x，所以咱们用的openvino版本肯定不同。
